### ISSUE TITLE
Test case fail

### ISSUE THREAD

**Issue by Maesla** [Unity-Technologies/com.unity.search.extensions#46]
This test refers to the main project and fails
https://github.com/Unity-Technologies/com.unity.search.extensions/blame/cd2027929cb6167a2f413c53c51457d3a9610145/package/Indexing/CustomIndexationTests.cs#L58

![image](https://github.com/Unity-Technologies/com.unity.search.extensions/assets/25863696/a93c788d-c5d3-4bd6-84a8-cce10175f21c)

**Comment by Maesla** [comment]
Hi, this is still happening. Why is this test in the package or why was the issue closed?

Thanks

![image](https://github.com/user-attachments/assets/4a3c0eb1-f4a6-47da-8878-d40754bc30a5)
ValidateCustomIndexation(t:shader sh_rendertype=opaque [Assets/Materials/SurfaceShader.shader] => 1 ) (0,042s)
---
Query t:shader sh_rendertype=opaque yielded 0 expected was 1
  Expected: 1
  But was:  0

**Comment by RichardWepnerPD** [comment]
The issue still occurs in version 1.0.1, which is the currently most recent version of this package.

With a unit test failing, it's much more difficult to reliably get usable results out of the unit tests in a CI. Instead of just invoking the automated tests and retrieving the test results directly, a filter would need to be applied to filter out false negatives. The easiest way to solve the issue would be to get rid of this package, which would be unfortunate.

Are there any workarounds available to prevent the test from failing? (Would the test not fail if there was a shader with opaque render type in the project?)

**Comment by hanachiru** [comment]
> Are there any workarounds available to prevent the test from failing? (Would the test not fail if there was a shader with opaque render type in the project?)

I have confirmed that placing the `.shader` with sh_rendertype=opaque at `Assets/Materials/SurfaceShader.shader` passes the test. :)

**Comment by hanachiru** [comment]
`testables` in `manifest.json` do not work if `UNITY_INCLUDE_TESTS` is not defined in `defineConstraints` in `com.unity.search.extensions.editor.asmdef`.

```json
{
  "dependencies": {
    "com.unity.search.extensions": "https://github.com/Unity-Technologies/com.unity.search.extensions.git?path=package",
    ...
  },
  "testables": [

  ]
}
```

https://github.com/Unity-Technologies/com.unity.search.extensions/blob/4996b11aa61dd5b0bdda66b897ac1a15b9d58c72/package/com.unity.search.extensions.editor.asmdef#L17

In my opinion, it is better to separate asmdef for editor and asmdef for test.
I would like to define an asmdef for test, but it does not seem to accept PRs.

**Comment by Maesla** [comment]
Hi @hanachiru!

Since this bug was closed, maybe you can open a new one referring this one, so we can try again to get it fixed.

Or @lochrist, please reopen the issue

**Comment by hanachiru** [comment]
@Maesla 

I created a new Issue. Thank you!
https://github.com/Unity-Technologies/com.unity.search.extensions/issues/52
