### ISSUE TITLE
"Used by" dependencies not found correctly for textures used by materials

### ISSUE THREAD

**Issue by ghost** [Unity-Technologies/com.unity.search.extensions#8]
When integrating the dependency viewer into our production project, textures referenced by materials won't be shown properly as "used by" dependencies.
![dependency_viewer_used_by_issue](https://user-images.githubusercontent.com/24388747/132051133-05ee8f1b-16c1-47d6-87f8-c94a19a76ba6.png)

In an otherwise empty project, the same material and texture combination is evaluated correctly.

Tested with Unity 2020.3.0 and 2020.3.17, Quick Search 3.0.0-preview.15, Search Extensions 1.0.4.

We'd be willing to share our project for debugging purposes if needed.

**Comment by jschmidt42** [comment]
Hi @MiFrilke, can you check if you still repro this issue with the latest version? I cannot repro it myself.
Thanks,

**Comment by jschmidt42** [comment]
Please use com.unity.quicksearch@3.0.0-preview.22 too if you are on 20.3.

**Comment by MiFrilke** [comment]
Using Unity 2020.3.23f1 with QuickSearch package version 3.0.0-preview.22 and Search Extensions package version 1.1.0.

It now looks a bit more in line with with what I'd expect (dual column layout), but still does not correctly show if a texture is used by a material:
![image](https://user-images.githubusercontent.com/24388747/143919447-8772eb88-8f74-4e94-82b8-0b8274115e65.png)

Also I had to fix a few compiler errors in the DependencyGraphViewer.cs:
- One use of **??=** null-coalescing assignment operator
- One use of "foo is **not** bar"
- One use of unavailable **m_Parent** field on DependencyGraphViewer

**Comment by jschmidt42** [comment]
Hmm ok that is weird. Would you able to zip a small project which reproduce the issue? I will debug from there.

> One use of ??= null-coalescing assignment operator

I will revert these changes. I guess they do not work with 2020.3

**Comment by MiFrilke** [comment]
I'm not sure if I can manage a "small" project which reproduces the issue. When testing in a mostly empty project, everything works fine. But when testing in our full code base, it behaves like reported here.
Luckily we have an older code refactor project which includes minimal assets, so compressed it should be around 250MB. 

I can't share the project publicly though, can we perhaps move this conversation to email/slack? I'm a guest on the Unity slack (f.mielke), otherwise hit me up via email: f.mielke at mimimi.games.

**Comment by jschmidt42** [comment]
@MiFrilke yes you can DM me by starting a conversation on https://forum.unity.com/members/jonathans42.1671063/ or you can reach me on the Unity Discord **Jonathan Schmidt#6360**

**Comment by jschmidt42** [comment]
@MiFrilke I added a new test suite for 20.3 with com.unity.quicksearch package to checkout for compilation issues:
https://github.com/Unity-Technologies/com.unity.search.extensions/pull/20

**Comment by jschmidt42** [comment]
I figured out the issue is issue is because we do not yet support scanning binary YAML files. If you turn on Text mode in the preferences, then if should work as expected. We try to add support for binary YAML file later.

![image](https://user-images.githubusercontent.com/4054655/146580094-3d5bab69-6515-44a0-ae5c-f626d11e1dc6.png)

Until then I wish you some great holidays. 🎅
